# -*- coding: utf-8 -*-

EXECUTION_TEST_TEMPLATES_PATH = "test/"
TEST_TEMPLATES_PATH = "./test"
TEST_REQUEST_LOG_FILENAME = 'logs/test_request_%d.log'
TEST_RUNNER_DJANGO_MANAGE_PARAMETER = "manage.py"
TEST_RUNNER_DJANGO_TEST_PARAMETER = "test"
TEST_RUNNER_NOSE_PARAMETER = "nose"
TEST_RUNNER_PYTEST_PARAMETER = "pytest"
TEST_RUNNER_TYPE_PARAMETER = "-m"
TEST_RUNNER_UNITTEST_PARAMETER = "unittest"
TEST_RUNNER_VERBOSITY_PARAMETER = "-v"
