# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def data_migrations(apps, schema_editor):
    Environment = apps.get_model("testing", "Environment")

    for _ in range(0, 100):
        environment = Environment()
        environment.is_available = True
        environment.save()


def reverse_data_migrations(apps, schema_editor):
    Environment = apps.get_model("testing", "Environment")

    Environment.objects.all().delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True, verbose_name='available?')),
            ],
            options={
                'verbose_name': 'Environment',
                'verbose_name_plural': 'Environments',
            },
        ),
        migrations.CreateModel(
            name='Requester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Requester',
                'verbose_name_plural': 'Requesters',
            },
        ),
        migrations.CreateModel(
            name='TestRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('template', models.CharField(max_length=255, verbose_name='template')),
                ('status', models.IntegerField(choices=[(0, 'Requested'), (1, 'Succeeded'), (2, 'Failed')], verbose_name='status')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.Environment', verbose_name='environment')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.Requester', verbose_name='requester')),
                ('test_runner', models.IntegerField(choices=[(0, 'unittest'), (1, 'py.test'), (2, 'nose'), (3, 'Django TestCase')], verbose_name='test runner')),
                ('log', models.TextField(blank=True, null=True, verbose_name='log')),
            ],
            options={
                'verbose_name': 'Test Request',
                'verbose_name_plural': 'Test Requests',
            },
        ),
        migrations.RunPython(data_migrations, reverse_code=reverse_data_migrations),
    ]
